### ISSUE TITLE
Compilation for Fedora 21 

### ISSUE THREAD

**Issue by emilio1234** [Ifsttar/I-Simpa#49]
I compiled I-Simpa on fedora 21 with no major hassle. I had to:

1. Manually install boost_1_60_0 and wxWidgets-3.1.0

2. Change the minimum cmake verion in CMakeLists.txt to 3.0.0

3. Make sure to cmake with python2.7: "cmake -DPYTHON_INCLUDE_DIR=/usr/include/python2.7/ -DPYTHON_LIBRARY=/usr/lib64/libpython2.7.so"

I uploaded 3ds files and did some meshing... everything seems to be working so far.  

attached is ldd output for isimpa 
[dependency.txt](https://github.com/Ifsttar/I-Simpa/files/529317/dependency.txt)

**Comment by nicolas-f** [comment]
Hi,

Thanks for the feedback.

We have a lot of works to do in order to publish a release to major linux distribution, but this is our goal.

Best regards,

**Comment by emilio1234** [comment]
Hi. I started working as well on this. done some work especially in the
binary files compatability.  Let me know if you want to join forces.

Emil

**Comment by caceres** [comment]
Good night:
I've compiled I-Simpa in Ubuntu 16.04

1º) compiled boost 1.60
2º) compiled wxWidgets 3.1 _--disable-shared_ and _--with-opengl_
3º) installed dependence from .travis.yml

When I execute I-Simpa:

ASSERT INFO:
../src/gtk/dc.cpp(285): assert ""cr"" failed in wxPaintDCImpl(): using wxPaintDC without being in a native paint event

ASSERT INFO:
../src/common/dcgraph.cpp(351): assert ""IsOk()"" failed in SetTextForeground(): wxGCDC(cg)::SetTextForeground - invalid DC

ASSERT INFO:
../src/common/dcgraph.cpp(365): assert ""IsOk()"" failed in SetTextBackground(): wxGCDC(cg)::SetTextBackground - invalid DC

and later in Messages Console:

 Error:OpenGL error 1280

Other little problem in Python Console:

Language en_US is not avaible for this module :
/home/damian/isimpa-install/UserScript/moveto_vertex\
Traceback (most recent call last):
  File "/home/damian/isimpa-install/SystemScript/uilocale/__init__.py", line 13, in InstallUiModule
    locale_dict=gettext.translation("messages",localdir,languages=[language])
  File "/usr/lib/python2.7/gettext.py", line 487, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'messages'

and the same problem with source_tools, preceiv_sourceTracker, ...

Thank you
